Add some temporary printlns
Because who doesn't love println debugging?

Now, running the (failing) test case added in the previous commit, we'll
see:

```
---- toplevel::test::multi_use_with_layered_dirs stdout ----
parsing file at path='"root.witx"' root='"/"'
canonical-path='"/root.witx"'

found a use statement, parsing file at "subdir/child.witx"
parsing file at path='"subdir/child.witx"' root='"/"'
canonical-path='"/subdir/child.witx"'

found a use statement, parsing file at "sibling.witx"
parsing file at path='"sibling.witx"' root='"/"'
canonical-path='"/sibling.witx"'
thread 'toplevel::test::multi_use_with_layered_dirs' panicked at 'parse: Io("/sibling.witx", Custom { kind: Other, error: "mock fs: file not found" })', src/toplevel.rs:151:10
```

Note that root is always `/` even when we're evaluating the paths found
in a document that lives in a subdirectory! See how the canonical path
in the last block resolves to '/sibling.witx'?

We found you, Mr. Bug 🐛 🔍😃